//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loopscale.DataAccess.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public long ProfileId { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public int ProfileTypeId { get; set; }
        public Nullable<long> FamilyId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string Mobile { get; set; }
        public int Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FamilyName { get; set; }
        public string HomeAddressLine1 { get; set; }
        public string HomeAddressLine2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
        public string EmployeeName { get; set; }
        public string Occupation { get; set; }
        public string OfficeAddressLine1 { get; set; }
        public string OfficeAddressLine2 { get; set; }
        public string OfficeCity { get; set; }
        public Nullable<int> OfficeStateId { get; set; }
        public string OfficeZip { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeEmail { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsValidProfile { get; set; }
        public string ImageId { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<long> SyncId { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string QboDisplayName { get; set; }
        public bool Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual ProfileTypeMaster ProfileTypeMaster { get; set; }
        public virtual RelationshipMaster RelationshipMaster { get; set; }
        public virtual StateMaster StateMaster1 { get; set; }
    }
}
